var data = [
  {"state":"Alabama", value:"0.769"},
  {"state":"Alaska", value:"0.477"},
  {"state":"Arizona", value:"0.194"},
  {"state":"Arkansas", value:"0.782"},
  {"state":"California", value:"0.705"},
  {"state":"Colorado", value:"0.687"},
  {"state":"Connecticut", value:"0.956"},
  {"state":"Delaware", value:"0.673"},
  {"state":"Florida", value:"0.404"},
  {"state":"Georgia", value:"0.932"},
  {"state":"Hawaii", value:"0.353"},
  {"state":"Idaho", value:"0.677"},
  {"state":"Illinois", value:"0.945"},
  {"state":"Indiana", value:"0.081"},
  {"state":"Iowa", value:"0.306"},
  {"state":"Kansas", value:"0.123"},
  {"state":"Kentucky", value:"0.764"},
  {"state":"Louisiana", value:"0.983"},
  {"state":"Maine", value:"0.541"},
  {"state":"Maryland", value:"0.978"},
  {"state":"Massachusetts", value:"0.147"},
  {"state":"Michigan", value:"0.105"},
  {"state":"Minnesota", value:"0.512"},
  {"state":"Missouri", value:"0.274"},
  {"state":"Mississippi", value:"0.731"},
  {"state":"Montana", value:"0.187"},
  {"state":"North Carolina", value:"0.703"},
  {"state":"North Dakota", value:"0.999"},
  {"state":"Nebraska", value:"0.24"},
  {"state":"New Hampshire", value:"0.118"},
  {"state":"New Jersey", value:"0.188"},
  {"state":"New Mexico", value:"0.01"},
  {"state":"Nevada", value:"0.431"},
  {"state":"New York", value:"0.98"},
  {"state":"Ohio", value:"0.117"},
  {"state":"Oklahoma", value:"0.356"},
  {"state":"Oregon", value:"0.176"},
  {"state":"Pennsylvania", value:"0.773"},
  {"state":"Rhode Island", value:"0.156"},
  {"state":"South Carolina", value:"0.232"},
  {"state":"South Dakota", value:"0.246"},
  {"state":"Tennessee", value:"0.191"},
  {"state":"Texas", value:"0.837"},
  {"state":"Utah", value:"0.72"},
  {"state":"Virginia", value:"0.465"},
  {"state":"Vermont", value:"0.666"},
  {"state":"Washington", value:"0.275"},
  {"state":"Wisconsin", value:"0.424"},
  {"state":"West Virginia", value:"0.93"},
  {"state":"Wyoming", value:"0.649"}]
